import { DashboardData } from '../types/dashboard.js';

export const INITIAL_MOCK_DATA: DashboardData = {
  systemState: 'NORMAL',
  processingMode: 'STREAM',
  reason: 'Nominal load. Incoming traffic matches processing throughput.',
  traffic: {
    incomingTraffic: '1,000 events/min',
    incomingEventsPerSec: 16.7,
    workerThroughput: '950 events/min',
    workerEventsPerSec: 15.8,
    queuePressurePercent: 12,
  },
  criticalProtection: {
    received: 1250,
    processed: 1225,
    queued: 25,
    lost: 0, // CRITICAL LOST: 0
    sheddingStatus: 'DISABLED',
    isProtected: true,
  },
  lanes: [
    {
      tier: 'TIER 1 — CRITICAL',
      name: 'Orders & Payments',
      description: 'Business-critical financial & transactional events',
      processingMode: 'Immediate / Individual',
      queueCount: 25,
      capacity: 2000,
      pressurePercent: 1.25,
      status: 'PROTECTED',
      statusColor: 'green',
    },
    {
      tier: 'TIER 2 — HIGH',
      name: 'Inventory Activity',
      description: 'Stock updates and catalog reservation changes',
      processingMode: 'Adaptive Priority',
      queueCount: 140,
      capacity: 2000,
      pressurePercent: 7.0,
      status: 'HIGH',
      statusColor: 'blue',
    },
    {
      tier: 'TIER 3 — LOW',
      name: 'Clicks & Application Logs',
      description: 'User telemetry, clickstream & diagnostic traces',
      processingMode: 'Adaptive Batch / Defer / Shed',
      queueCount: 2340,
      capacity: 3000,
      pressurePercent: 78.0,
      status: 'ADAPTIVE',
      statusColor: 'purple',
    },
  ],
  counters: {
    totalProcessed: 18450,
    criticalProcessed: 1225,
    nonCriticalProcessed: 17225,
    batchedCount: 14200,
    deferredCount: 180,
    shedCount: 0,
  },
  latencyHistory: [
    { time: '10:32:00', criticalLatency: 14, nonCriticalLatency: 18 },
    { time: '10:32:05', criticalLatency: 15, nonCriticalLatency: 22 },
    { time: '10:32:10', criticalLatency: 16, nonCriticalLatency: 28 },
    { time: '10:32:15', criticalLatency: 15, nonCriticalLatency: 45 },
    { time: '10:32:20', criticalLatency: 15, nonCriticalLatency: 82 },
    { time: '10:32:25', criticalLatency: 16, nonCriticalLatency: 120 },
    { time: '10:32:30', criticalLatency: 14, nonCriticalLatency: 154 },
    { time: '10:32:35', criticalLatency: 15, nonCriticalLatency: 198 },
    { time: '10:32:40', criticalLatency: 16, nonCriticalLatency: 240 },
    { time: '10:32:45', criticalLatency: 15, nonCriticalLatency: 180 },
    { time: '10:32:50', criticalLatency: 14, nonCriticalLatency: 95 },
    { time: '10:32:55', criticalLatency: 15, nonCriticalLatency: 35 },
  ],
  recentDecisions: [
    {
      id: 'evt_101',
      time: '10:32:15',
      type: 'PAYMENT',
      priority: 'CRITICAL',
      decision: 'STREAM',
      status: 'Processed',
      reason: 'Critical payment: dedicated priority route, zero delay',
    },
    {
      id: 'evt_102',
      time: '10:32:16',
      type: 'ORDER',
      priority: 'CRITICAL',
      decision: 'STREAM',
      status: 'Processed',
      reason: 'Critical order: immediate individual dispatch',
    },
    {
      id: 'evt_103',
      time: '10:32:17',
      type: 'CLICK',
      priority: 'LOW',
      decision: 'BATCH',
      status: 'Added to batch',
      reason: 'Low priority: grouped into micro-batch (25 items)',
    },
    {
      id: 'evt_104',
      time: '10:32:18',
      type: 'LOG',
      priority: 'LOW',
      decision: 'DEFER',
      status: 'Deferred',
      reason: 'Queue pressure high: low-priority execution held',
    },
    {
      id: 'evt_105',
      time: '10:32:19',
      type: 'CLICK',
      priority: 'LOW',
      decision: 'SHED',
      status: 'Shed (Logged)',
      reason: 'Extreme overload: queue capacity exceeded safety threshold',
    },
  ],
};
